# roles/tftp/tasks/main.yml
---

- name: Install packages
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: tftp_packages
  tags: tftp

- name: Ensure service is started
  service:
    name: "{{ tftp_service }}"
    state: started
    enabled: true
  tags: tftp

- name: Install configuration file
  template:
    dest: /etc/xinetd.d/tftp
    src: etc_xinetd.d_tftp.j2
  notify:
    - restart tftp
  tags: tftp
